### ISSUE TITLE
placeholder追加 ( Imperatrix_AddGradePrefix_<Prefix> )

### ISSUE THREAD

**Issue by LazyGon** [okocraft/Imperatrix#1]
Javascriptで制作したsetprefix_showの代替placeholder

**Comment by akaregi** [comment]
具体的な機能はなんでしょ

**Comment by LazyGon** [comment]
> 具体的な機能はなんでしょ

プレイヤーの持つ権限に応じて*<Prefix>を返すプレホル
権限によって*の色がわかる（若しくは#）になる

**Comment by LazyGon** [comment]
あれ、\<Prefix\>きえた()
*\<Prefix\>です

**Comment by LazyGon** [comment]
例えば%Imperatrix_AddGradePrefix_&7[&c死&7]%を私が見ると、&7[&c死&7]&6#&rを返す

**Comment by akaregi** [comment]
Placeholder 名妙に長いからもうすこしどうにかならないか?
`%Imperatrix_PermPrefix_<Prefix>%` みたいに

**Comment by LazyGon** [comment]
それでも構わないです
PermPrefixで作ってみる

**Comment by LazyGon** [comment]
不必要になったので、棄却
