### ISSUE TITLE
Placeholder 追加: %Imperatrix_hasitem%

### ISSUE THREAD

**Issue by LazyGon** [okocraft/Imperatrix#7]

**Comment by LazyGon** [comment]
タイトルミス
Imperatrix hasitem

**Comment by akaregi** [comment]
タイトルだけなら ↑ の Edit ボタンからいじれるよ

**Comment by akaregi** [comment]
機能 is 何

**Comment by LazyGon** [comment]
手持ちに条件のアイテムが有るか判定する、例えば
%Imperatrix_hasitem_mat:stone,amt:5,lore:test1|test2%
だったら、手持ちに、test1、test2のloreを持った石が5個以上あるかどうか判定

**Comment by LazyGon** [comment]
この前ディスに出して困らせたのはそれのエンチャントの判定部分

**Comment by akaregi** [comment]
パーサ作ったほうがよさそうね...

**Comment by LazyGon** [comment]
パーサとはどういう...?

**Comment by akaregi** [comment]
プレースホルダーをまとめて処理するやつではなくパラメタの `mat:stone,amt:5,lore:test1` だけを処理するやつ

**Comment by akaregi** [comment]
`:` で切り分けて `mat:stone`、`amt:5`、`lore:test1` にして...

**Comment by akaregi** [comment]
.... `mat` は `material` のほうがいいし `amt` も `amount` のほうがいいと思うのだが

**Comment by LazyGon** [comment]
まぁそのへんのフォーマットはいくらでも変えられるんですが...とりあえず、コードの中のパーサ部分(パーサっていうのを知らなかった)はできてる

Utilitiesに入れときますね

**Comment by akaregi** [comment]
新しくクラス作ってそこでやって。`Item` クラスとか。

**Comment by akaregi** [comment]
`Utilities` は汎用的なメソッドをまとめておくクラスであって、特定の用途に特化したメソッドをぶち込むクラス**ではない**。

**Comment by LazyGon** [comment]
いえ、identifierを打ち込んだら先頭から_の文字までを削ってくれるメソッドでも作ろうかと

**Comment by LazyGon** [comment]
...replaceAllで一発か

**Comment by akaregi** [comment]
#8
